<a href="https://www.kaggle.com/code/hilalalpak/numpynotes?scriptVersionId=178349082" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
import numpy as np

##Listeden farkı; verimli veri saklama (sabit tip veri, hız) ve yüksek seviyeden işlemler(az çaba, çok iş) yapılabilir.

In [2]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [3]:
##Klasik yol ile;
a = [1, 4, 7, 12]
b = [2, 9, 18, 13]
ab = []
for i in range(0, len(a)):
      ab.append(a[i] * b[i])

In [4]:
##Numpy ile;
a = np.array([1, 4, 7, 12])
b = np.array([2, 9, 18, 13])
a * b

array([  2,  36, 126, 156])

In [5]:
###Sıfırdan array oluşturma;
np.array([3, 5, 7, 2, 9])
type(np.array([3, 5, 7, 2, 9]))

np.zeros(10, dtype=int) 
np.random.randint(0 , 10, size=10) 
np.random.normal(0, 10, (3, 4))

array([3, 5, 7, 2, 9])

numpy.ndarray

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

array([9, 3, 2, 7, 4, 3, 4, 1, 6, 0])

array([[ -7.23281517,   1.76972623,   0.8621193 ,  -3.21828388],
       [  2.66164873,  -4.12317917, -12.45064667,   1.63157494],
       [  4.7124986 ,  -9.64264011,  -8.65026396,  -4.98534135]])

In [6]:
a = np.random.randint(10, size=5)

In [7]:
a.ndim,a.shape,a.size,a.dtype

(1, (5,), 5, dtype('int64'))

In [8]:
##Boyut değiştirme;
np.random.randint(1, 10, size=9)
np.random.randint(1, 10, size=9).reshape(3, 3)

array([8, 3, 8, 3, 2, 4, 4, 1, 4])

array([[6, 8, 6],
       [9, 5, 9],
       [4, 3, 6]])

#Eleman sayısı ile boyut sayısı tutarlı olmalıdır.

In [9]:
##Index seçimi;
a[0]
a[0:5]
a[0] = 14

2

array([2, 1, 0, 0, 6])

In [10]:
m = np.random.randint(10, size=(3, 5))
m

array([[4, 0, 0, 9, 3],
       [7, 3, 1, 5, 8],
       [5, 9, 6, 6, 7]])

In [11]:
m[0, 1]
m[2, 3] = 7
m

0

array([[4, 0, 0, 9, 3],
       [7, 3, 1, 5, 8],
       [5, 9, 6, 7, 7]])

In [12]:
m[1, 4] = 4.2
m

array([[4, 0, 0, 9, 3],
       [7, 3, 1, 5, 4],
       [5, 9, 6, 7, 7]])

Float ifade girilse dahi tek tip veri tuttuğu için integer ile atama yapar.

In [13]:
m[:, 0]
m[1, :]
m[0:2, 0:3]

array([4, 7, 5])

array([7, 3, 1, 5, 4])

array([[4, 0, 0],
       [7, 3, 1]])

In [14]:
##Fancy index;
v = np.arange(0, 30, 3)
v
catch = [1, 2, 3]
v[catch]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

array([3, 6, 9])

In [15]:
n = np.array([2, 6, 7, 10, 9])
ab = []
n[n < 8]
n[n == 7]
n[n != 10]

array([2, 6, 7])

array([7])

array([2, 6, 7, 9])

##Klasik yol ile; 
for i in x:
      if i < 2:
       ab.append(i) 

In [16]:
##Matematiksel & istatistiksel işlemler;
e = np.array([4, 6, 12, 3, 18])
e**2
e-1

array([ 16,  36, 144,   9, 324])

array([ 3,  5, 11,  2, 17])

##Numpy methodları ile;
   np.subtract(e, 1)
     np.add(e, 2)
       np.min(e)
         np.max(e)
           np.sum(e)
             np.mean(e)
               np.var(e)

##İki bilinmeyen denklem çözme;

5*x0 + x1 = 12
x0 + 3*x1 = 10

a = np.array([[5, 1], [1, 3]])
b = np.array([12,10])
np.linalg.solve(a, b)